version: "3"
services:
  tf_jupyter:
    build: ./
    ports:
     - "8888:8888"
    deploy:
      resources:
        reservations:
          devices:
           - driver: nvidia
             capabilities: [utility, compute, video]
    command: "jupyter notebook"